themetours/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'themetours.views.home', name='home'),
    # url(r'^themetours/', include('themetours.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', 'themetours.views.index'),

    url(r'^airsales/', 'themetours.views.sales'),
    url(r'^json_sales/service_type/(\d+)', 'themetours.views.service_related_models'),
    url(r'^json_airsales', 'themetours.views.json_sales'),
    url(r'^update_airsales/(-?\d+)', 'themetours.views.update_airsale'),


    url(r'^purchases/', 'themetours.views.purchases'),
    url(r'^json_purchases/', 'themetours.views.json_purchases'),
    url(r'^update_airpurchases/(-?\d+)', 'themetours.views.update_airpurchases'),
    url(r'^update_saleairpurchase/(-?\d+)', 'themetours.views.update_saleairpurchase'),
    url(r'^purchaseSaleInfo/(-?\d+)', 'themetours.views.purchaseSaleInfo'),
    url(r'^delete_airsales/', 'themetours.views.delete_airsales'),

    url(r'^reports/', 'themetours.views.reports'),

    url(r'^config/clients/', 'themetours.views.clients'),
    url(r'^config/json_clients/', 'themetours.views.json_clients'),
    url(r'^config/update_clients/(-?\d+)', 'themetours.views.update_client'),
    url(r'^config/delete_client/', 'themetours.views.delete_client'),

    url(r'^config/services/', 'themetours.views.services'),
    url(r'^config/json_services/', 'themetours.views.json_services'),
    url(r'^config/update_services/(-?\d+)', 'themetours.views.update_service'),
    url(r'^config/delete_service/', 'themetours.views.delete_service'),

    url(r'^config/suppliers/', 'themetours.views.suppliers'),
    url(r'^config/json_suppliers/', 'themetours.views.json_suppliers'),
    url(r'^config/update_suppliers/(-?\d+)', 'themetours.views.update_supplier'),
    url(r'^config/delete_supplier/', 'themetours.views.delete_supplier'),

    url(r'^print/airsales/(-?\d+)', 'themetours.views.print_airsales'),

    #url(r'^config/users', 'themetours.views.users'),
    #url(r'^config/json_users', 'themetours.views.json_users'),
    #url(r'^config/update_users', 'themetours.views.update_user'),
)

themetours/models.py
import json
from django.db import models

class Service(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=15)
    code = models.CharField(max_length=3)
    service_tax = models.DecimalField(max_digits=5, decimal_places=2)
    education_cess = models.DecimalField(max_digits=5, decimal_places=2)
    higher_secondary = models.DecimalField(max_digits=5, decimal_places=2)
    from_date = models.DateField(blank=False)
    to_date = models.DateField(null=True)

    # ....
    def to_json(self):
        return json.dumps([str(self.id), str(self.id), self.name, self.code, str(self.service_tax), str(self.education_cess), str(self.higher_secondary), str(self.from_date), str(self.to_date)])

    def get_query_set(self):
        return super(Service, self).get_query_set().filter(is_deleted=False)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = "service"
        verbose_name_plural = "services"

class Client(models.Model):
    SALUATION_MAP = (
        ('Mr', 'Mr.'),
        ('Ms', 'Ms.'),
        ('Mrs', 'Mrs.'),
        ('Smt', 'Smt.'),
        ('Shri', 'Shri '),
        ('Mast', 'Mast.'),
        ('Miss', 'Miss.'),
        ('Dr', 'Dr.'),
        ('Prof', 'Prof.'),
        (' ', ' '),
    )

    id = models.AutoField(primary_key=True)
    saluation = models.CharField(max_length=7, choices=SALUATION_MAP)
    company = models.CharField(max_length=150, blank=True)
    first_name = models.CharField(max_length=75)
    last_name = models.CharField(max_length=75)
    address_line1 = models.CharField(max_length=250)
    address_line2 = models.CharField(max_length=250)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=75)
    zip = models.BigIntegerField(max_length=7)
    country = models.CharField(max_length=30)
    contact_phone = models.BigIntegerField(max_length=13)
    email = models.EmailField(max_length=75)
    pan_no = models.CharField(max_length=15)
    reference_name = models.CharField(max_length=200)
    is_deleted = models.BooleanField(default=False)

    def get_query_set(self):
        return super(Client, self).get_query_set().filter(is_deleted=False)

    def _get_full_name(self):
        return '%s %s %s' % (self.saluation, self.first_name, self.last_name)
    full_name = property(_get_full_name)

    def _get_display_name(self):
        if None == self.company or 0 == len(self.company):
            return self.full_name
        else:
            return self.company
    display_name = property(_get_display_name)

    def to_json(self):
        return json.dumps([str(self.id), str(self.id), self.company, self.display_name, self.city, self.contact_phone, self.email, self.reference_name])

    class Meta:
        verbose_name = "client"
        verbose_name_plural = "clients"

    # ...
    def __unicode__(self):
        return self.display_name

class Supplier(models.Model):
    SALUATION_MAP = (
        ('Mr', 'Mr.'),
        ('Ms', 'Ms.'),
        ('Mrs', 'Mrs.'),
        ('Smt', 'Smt.'),
        ('Shri', 'Shri '),
        ('Mast', 'Mast.'),
        ('Miss', 'Miss.'),
        ('Dr', 'Dr.'),
        ('Prof', 'Prof.'),
        (' ', ' '),
    )

    id = models.AutoField(primary_key=True)
    service_type = models.ForeignKey(Service)
    company = models.CharField(max_length=150, blank=True)
    saluation = models.CharField(max_length=6, choices=SALUATION_MAP)
    first_name = models.CharField(max_length=75)
    last_name = models.CharField(max_length=500)
    address_line1 = models.CharField(max_length=250)
    address_line2 = models.CharField(max_length=250)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=75)
    zip = models.BigIntegerField(max_length=7)
    country = models.CharField(max_length=30)
    contact_phone = models.BigIntegerField(max_length=13)
    email = models.EmailField(max_length=75)
    pan_no = models.CharField(max_length=15, blank=True)
    service_reg_no = models.CharField(max_length=20, blank=True)
    is_deleted = models.BooleanField(default=False)

    def _get_full_name(self):
        return '%s %s %s' % (self.saluation, self.first_name, self.last_name)
    full_name = property(_get_full_name)

    def _get_display_name(self):
        if None == self.company or 0 == len(self.company):
            return self.full_name
        else:
            return self.company
    display_name = property(_get_display_name)

    def to_json(self):
        return json.dumps([str(self.id), str(self.id), self.service_type.code, self.company, self.full_name, self.city, self.contact_phone, self.email])

    def get_query_set(self):
        return super(Supplier, self).get_query_set().filter(is_deleted=False)

    # ...
    def __unicode__(self):
        return self.display_name

    class Meta:
        verbose_name = "supplier"
        verbose_name_plural = "suppliers"

class Sale(models.Model):
    id = models.AutoField(primary_key=True)
    service_type = models.ForeignKey(Service)
    client = models.ForeignKey(Client)
    sales_transaction_no = models.CharField(max_length=25, blank=True)
    sales_date = models.DateField();
    service_tax = models.DecimalField(max_digits=19, decimal_places=2)
    education_cess = models.DecimalField(max_digits=19, decimal_places=2)
    higher_secondary = models.DecimalField(max_digits=19, decimal_places=2)
    additional_service_charge = models.DecimalField(max_digits=19, decimal_places=2)
    discount = models.DecimalField(max_digits=19, decimal_places=2)
    round_off = models.DecimalField(max_digits=19, decimal_places=2)
    total = models.DecimalField(max_digits=19, decimal_places=2, blank=True)
    when_date =  models.DateTimeField(auto_now = True, auto_now_add=True)
    is_deleted = models.BooleanField(default=False)

    def to_json(self):
        return json.dumps([str(self.id), str(self.id), self.service_type.code, self.client.display_name, self.sales_transaction_no, str(self.id)])

    def get_query_set(self):
        return super(Sale, self).get_query_set().filter(is_deleted=False)

    def save(self, *args, **kwargs):
        super(Sale, self).save(*args, **kwargs) # Call the "real" save() method.
        self.sales_transaction_no = self.service_type.code+ '/'+ str(self.id)
        super(Sale, self).save(*args, **kwargs) # Call the "real" save() method.

    # ...
    def __unicode__(self):
        return str(self.id)

    class Meta:
        verbose_name = "sale"
        verbose_name_plural = "sales"

class Purchase(models.Model):
    id = models.AutoField(primary_key=True)
    sales = models.ForeignKey(Sale)
    purchase_transaction_no = models.CharField(max_length=25, blank=True)
    supplier = models.ForeignKey(Supplier)
    service_tax = models.DecimalField(max_digits=19, decimal_places=2, blank=True)
    education_cess = models.DecimalField(max_digits=19, decimal_places=2, blank=True)
    higher_secondary = models.DecimalField(max_digits=19, decimal_places=2, blank=True)
    tds = models.DecimalField(max_digits=19, decimal_places=2, blank=True)
    discount = models.DecimalField(max_digits=19, decimal_places=2, blank=True)
    round_off = models.DecimalField(max_digits=19, decimal_places=2, blank=True)
    when_date =  models.DateTimeField(auto_now = True, auto_now_add=True)
    purchase_actual = models.DecimalField(max_digits=19, decimal_places=2, blank=False)
    total = models.DecimalField(max_digits=19, decimal_places=2, blank=True)
    is_deleted = models.BooleanField(default=False)

    # ...
    def __unicode__(self):
        return str(self.id)

    def get_query_set(self):
        return super(Purchase, self).get_query_set().filter(is_deleted=False)

    def save(self, *args, **kwargs):
        super(Purchase, self).save(*args, **kwargs) # Call the "real" save() method.
        self.purchase_transaction_no = 'P/' +self.sales.service_type.code+ '/'+ str(self.id)
        super(Purchase, self).save(*args, **kwargs) # Call the "real" save() method.

    def to_json(self):
        return json.dumps([self.id, self.id, self.purchase_transaction_no, self.supplier.company, str(self.service_tax), str(self.education_cess), str(self.higher_secondary), str(self.tds), str(self.discount)])
    class Meta:
        verbose_name = "purchase"
        verbose_name_plural = "purchasers"

class PassengerInfo(models.Model):
    id = models.AutoField(primary_key=True)
    when_date =  models.DateTimeField(auto_now = True, auto_now_add=True)
    sales_transaction_no = models.ForeignKey(Sale)
    purchase_transaction_no = models.ForeignKey(Purchase)
    supplier = models.ForeignKey(Supplier)
    pax_name = models.CharField(max_length=150)
    transaction_no = models.CharField(max_length = 30)

    sector_from1 = models.CharField(max_length=5)
    sector_to1 = models.CharField(max_length=5)
    travel_date1 = models.DateField()
    airline_name1 = models.CharField(max_length=3)

    sector_from2 = models.CharField(max_length=5, blank=True, null=True)
    sector_to2 = models.CharField(max_length=5, blank=True, null=True)
    travel_date2 = models.DateField(blank=True, null=True)
    airline_name2 = models.CharField(max_length=3, blank=True, null=True)

    sector_from3 = models.CharField(max_length=5, blank=True, null=True)
    sector_to3 = models.CharField(max_length=5, blank=True, null=True)
    travel_date3 = models.DateField(blank=True, null=True)
    airline_name3 = models.CharField(max_length=3, blank=True, null=True)

    sector_from4 = models.CharField(max_length=5, blank=True, null=True)
    sector_to4 = models.CharField(max_length=5, blank=True, null=True)
    travel_date4 = models.DateField(blank=True, null=True)
    airline_name4 = models.CharField(max_length=3, blank=True, null=True)

    sector_from5 = models.CharField(max_length=5, blank=True, null=True)
    sector_to5 = models.CharField(max_length=5, blank=True, null=True)
    travel_date5 = models.DateField(blank=True, null=True)

templates/themetours/airsales.html
<div id="Sales" style="float:left;padding-bottom:8px">
  <button id="new-airsale"> Sale</button>
</div>
<div style="float:right;padding-bottom:8px" id="deleteRecord">
  <button id="delete-airsale"> Delete Sale</button>
</div>
<div id="airsales-dynamic"></div>
<script>
    function dumpElement( element ) {
	var elementDump;
	// dump element attributes
	var attrDump = '';
	var attribute;
	var dumpedAttribute;

	for( var i = 0; i < element.attributes.length; i++) {
            attribute = element.attributes[i];
            // skip every not specified attribute (useful for example in IE)
            if ( attribute.specified == false ) continue;
            // current attribute dump
            dumpedAttribute = attribute.name + '="' + attribute.value + '"';
            // add current attribute to dump, separating attributes with whitespace
            attrDump += ((attrDump != '')?' ':'') + dumpedAttribute;
	}

	var tagName = element.tagName.toLowerCase();
	// note: innerHTML does not preserve code formatting
	// note: innerHTML on IE sets the tags names to uppercase (e.g. not W3C Valid)
	if( element.innerHTML == '' ) {
            // self closing tag syntax
            elementDump = '<' + tagName + ((attrDump != '')? ' '+attrDump : '') + '/>';

	} else {
            elementDump = '<' + tagName + ((attrDump != '')? ' '+attrDump : '') + '>' + element.innerHTML + '</' + tagName + '>';
	}
	return elementDump;
    }

    function getTotalBasic(prefix) {
	var totalBasic = 0.0;
	var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
	for (var i = 0; i < formCount; i++) {
	    totalBasic += getVal("#id_" + prefix + "-" + i + "-basic_fare");
	}
	return totalBasic;
    }

    function calculatePurchaseTotal(prefix) {
	var total = 0.0;
	var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
	for (var i = 0; i < formCount; i++) {
	    total += getVal("#id_" + prefix + "-" + i + "-service_tax");
	    total += getVal("#id_" + prefix + "-" + i + "-education_cess");
	    total += getVal("#id_" + prefix + "-" + i + "-higher_secondary");
	    total += getVal("#id_" + prefix + "-" + i + "-tds");
	    total = total - getVal("#id_" + prefix + "-" + i + "-discount");
	    total += getVal("#id_" + prefix + "-" + i + "-round_off");
	    total += getVal("#id_"+prefix+"-"+i+"-purchase_actual");
	    $("#id_" + prefix + "-" + i + "-total").val(total.toFixed(2));
	}
    };

    function calculateTaxes(prefix) {
	var totalBasic = getTotalBasic( prefix );
	var service_tax_per = getVal("#id_s-service_tax_per");
	var education_cess_per = getVal("#id_s-education_cess_per")
	var higher_secondary_per = getVal("#id_s-higher_secondary_per");

	$("#id_s-service_tax").val( (totalBasic * (service_tax_per )/ 100).toFixed(2) )
	$("#id_s-education_cess").val( (totalBasic * (education_cess_per)/ 100).toFixed(2) )
	$("#id_s-higher_secondary").val( (totalBasic * (higher_secondary_per)/ 100).toFixed(2) )

	return
    }

    function calculateTotal(prefix) {
	var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
	var total = 0.0;
	var tax_total = 0.0;

	for (var i = 0; i < formCount; i++) {
	    total += getVal("#id_" + prefix + "-" + i + "-basic_fare");
	    total += getVal("#id_" + prefix + "-" + i + "-airline_taxes");
	}

	total = total - getVal("#id_s-discount");
	total += getVal("#id_s-additional_service_charge");
	total += getVal("#id_s-round_off");

	calculateTaxes(prefix);
	tax_total += getVal("#id_s-service_tax");
	tax_total += getVal("#id_s-education_cess");
	tax_total += getVal("#id_s-higher_secondary");

	$("#id_air_tax").val(tax_total.toFixed(2));
	total += tax_total;
	$("#id_s-total").val(total.toFixed(2));
    }

    $( "#dialog:ui-dialog" ).dialog( "destroy" );
    var idCounter = new Date().getTime();
    function showDialog(id) {
	var unique_divId = idCounter++;
	var dynamicDiv = '<div id="'+ (unique_divId) +'"> </div>';
	var customDialog = $(dynamicDiv).load('/update_airsales/'+id)
	    .dialog({
		"autoOpen": false,
		"height": 500,
		"width": 890,
		"modal": true,
		"buttons": [{ text: (-1 == id ? 'Create' : "Update"),
		  id: "id_new_airsale",
		  click: function() {
		      calculateTotal('form');
		      var formdata = $.param($('#' + unique_divId +' form[name=airsale_form]').serializeArray());
		      $.ajax({
			  type: 'POST',
			  url: '/update_airsales/'+id,
			  dataType: 'json',
			  cache: false,
			  data: formdata,
			  success: function(data) {
			      $('#' + unique_divId +' form[name=airsale_form]').detach();
			      customDialog.dialog( 'destroy' );

			      if (-1 == id) {
				  sTable.dataTable().fnAddData(data);
			      } else {
				  sTable.dataTable().fnUpdate(data, fnGetSelectedRowId(sTable), false);
			      }
			  },

			  error: function(errors) {
			      $('#'+unique_divId).html(errors.responseText);
			  }
		      });
		  }
		},
		{
		    text: "Next",
		    id: "id_new_airsale_next",
		    click: function() {
			calculateTotal('form');
			var formdata = $.param($('#' + unique_divId +' form[name=airsale_form]').serializeArray());
			$.ajax({
			    type: 'POST',
			    url: '/update_airsales/'+id,
			    dataType: 'json',
			    cache: false,
			    data: formdata,
			    success: function(data) {
				$('#' + unique_divId +' form[name=airsale_form]').detach();
				$('#' + unique_divId).load("/update_saleairpurchase/"+data[0])
				customDialog
				    .dialog({
					buttons: [{text: 'Finish',
						   id: "id_finish_airpurchase",
						   click: function() {
						       $.ajax({
							   type: 'POST',
							   url: '/update_saleairpurchase/'+data[0],
							   dataType: 'json',
							   cache: false,
							   data: $.param($('#id_air_purchase').serializeArray()),
							   success: function(data) {
							       $('#id_air_purchase').detach();
							       customDialog.dialog( 'destroy' );
							   }
						       })
						   }
						  }]
				    })
				if (-1 == id) {
				    sTable.dataTable().fnAddData(data);
				} else {
				    sTable.dataTable().fnUpdate(data, fnGetSelectedRowId(sTable), false);
				}
			    },

			    error: function(errors) {
				$('#'+unique_divId).html(errors.responseText);
			    }
			});
		    }
		}],
		close: function() {
		    $('#' + unique_divId +' form[name=airsale_form]').detach();
		    $('#airsales-popup').dialog('close');
		}
	    });
	customDialog.dialog("open");
    }

    $("#new-airsale").button({
	icons: {
	    primary: "ui-icon-plusthick"
	}
    }).click(function() {
	showDialog(-1);
    });

    $("#delete-airsale").button({
	icons: {
	    primary: "ui-icon-minusthick"
	}
    }).click(function() {
	if (0 == sTable.$('input').serialize().length) {
	    myAlert("Please select a Row to delete");

	} else {
	    myConfirm("Are you sure you want to delete it ?",
		      function() {
			  $.ajax({
			      type: 'POST',
			      url: '/delete_airsales/',
			      dataType: 'json',
			      cache: false,
			      data: sTable.$('input').serialize() + '&csrfmiddlewaretoken='+'{{csrf_token}}',
			      success: function(data) {
				  $(sTable.fnSettings().aoData).each(function() {
				      if (-1 != $.inArray(this._aData[0], data)) {
					  sTable.fnDeleteRow( this.nTr );
				      }
				  });
			      },
			      error: function(errors) {
				  myAlert(errors);
			      }
			  });
		      },
		      function() {
			  myAlert('Canceled')
		      },
		      'Confirm Delete');
	}
    });

    /* Data set - can contain whatever information you want */
    var aDataSet = [ ];
    var sTable;
    $('#airsales-dynamic').html( '<table cellpadding="0" cellspacing="0" border="0" class="display" id="airsale-table"></table>' );
    sTable = $('#airsale-table').dataTable({
	"bJQueryUI": true,
	"aaData": aDataSet,
	"sPaginationType": "full_numbers",
	"bProcessing": true,
	"sAjaxSource": '/json_airsales/',
	"aoColumns": [
	    { "sTitle": "id",
	      "bSearchable": false,
	      "bVisible": false,
	    },
	    { "sTitle": "",
	      "fnRender": function (c, val) {
		  return "<input type='checkbox' name='check' value='" + val + "'>";
	      },
	      "bSearchable": false,
	      "bSortable": false
	    },
	    { "sTitle": "Service Name" },
	    { "sTitle": "Client Name" },
	    { "sTitle": "Sales Transaction No" },
	    { "sTitle": "",
	      "fnRender": function (c, val) {
		  return "<a href='javascript:void(0)'>Print</a>";
	      },
	      "bSearchable": false,
	      "bSortable": false
	    }
	],
    });

    $("#airsale-table tbody").click(function(event) {
	if ('checkbox' == event.target.type) {
	    return;
	}

	if ('Print' == event.target.innerHTML) {
	    var aData = sTable.fnGetData(event.target.parentNode.parentNode);
	    window.open('/print/airsales/'+aData[0], "Print Bill", "scrollbars=yes,menubar=no,fullscreen=no,height=600,width=1000", false);
	    return;
	}

	$(sTable.fnSettings().aoData).each(function () {
	    $(this.nTr).removeClass('row_selected');
	});

	$(event.target.parentNode).addClass('row_selected');

	var aData = sTable.fnGetData(event.target.parentNode);
	showDialog(aData[0]);
    });
</script>

templates/themetours/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title>Theme Tours &amp; Travels</title>
<link rel="stylesheet" href="/static/css/themetours.css">
<link rel="stylesheet" href="/static/css/jquery.ui.all.css">
<link rel="stylesheet" href="/static/css/jquery.dataTables_themeroller.css">
<script src="/static/js/jquery-1.7.2.js"></script>
<script src="/static/js/external/jquery.bgiframe-2.1.2.js"></script>
<script src="/static/js/ui/jquery.ui.core.js"></script>
<script src="/static/js/ui/jquery.ui.widget.js"></script>
<script src="/static/js/ui/jquery.ui.tabs.js"></script>
<script src="/static/js/ui/jquery.ui.button.js"></script>
<script src="/static/js/ui/jquery.ui.mouse.js"></script>
<script src="/static/js/ui/jquery.ui.draggable.js"></script>
<script src="/static/js/ui/jquery.ui.position.js"></script>
<script src="/static/js/ui/jquery.ui.resizable.js"></script>
<script src="/static/js/ui/jquery.ui.dialog.js"></script>
<script src="/static/js/ui/jquery.effects.core.js"></script>
<script src="/static/js/ui/jquery.effects.core.js"></script>
<script src="/static/js/ui/jquery.dataTables.js"></script>
<script src="/static/js/ui/jquery.ui.datepicker.js"></script>
<script src="/static/js/ui/jquery.ui.accordion.js"></script>
{% block jQueryScript %} {% endblock %}
</head>
<body>
<center>
<div class="page-container">
<div class="header-logo">
<img src="/static/images/logo.jpg" alt="Theme Tours & Travels Pvt Ltd" width="323" height="82" border="0" align="left" />
<br/>
</div>
{% block tabwidget %} {% endblock %}
</div>
</center>
</body>
</html>

templates/themetours/clients.html
<div id="Clients" style="float:left;padding-bottom:8px">
  <button id="new-client"> Client</button>
</div>
<div style="float:right;padding-bottom:8px" id="deleteRecord">
  <button id="delete-client"> Delete Client</button>
</div>
<div id="clients-dynamic"></div>
<script>
    var headers = [
		{ "sTitle": "id",
		  "bSearchable": false,
		  "bVisible": false,
		},
		{ "sTitle": "",
		  "fnRender": function (c, val) {
		      return "<input type='checkbox' name='check' value='" + val + "'>";
		  },
		  "bSearchable": false,
		  "bSortable": false
		},
		{ "sTitle": "Company" },
		{ "sTitle": "Name" },
		{ "sTitle": "City" },
		{ "sTitle": "Phone" },
		{ "sTitle": "Email" },
		{ "sTitle": "Reference Name"},
    ];
    curdView('{{csrf_token}}', 'client', 'client_form', headers, false, '/config/update_clients/', '/config/delete_client/', '/config/json_clients/' );
</script>

templates/themetours/purchases.html
<div id="purchases-dynamic"> </div>
<script>
    var headers = [
		{ "sTitle": "id",
		  "bSearchable": false,
		  "bVisible": false,
		},
		{ "sTitle": "",
		  "fnRender": function (c, val) {
		      return "<input type='checkbox' name='check' value='" + val + "'>";
		  },
		  "bSearchable": false,
		  "bSortable": false
		},
		{ "sTitle": "P Txn No"},
		{ "sTitle": "Company"},
		{ "sTitle": "S.T" },
		{ "sTitle": "E.C" },
		{ "sTitle": "H.S" },
		{ "sTitle": "Tds" },
		{ "sTitle": "discount" },
    ];
    curdView('{{csrf_token}}', 'purchase', 'purchase_form', headers, true, '/update_airpurchases/', '/delete_purchase/', '/json_purchases/' );
</script>

templates/themetours/update_airpurchase.html
<script>
    function calculatePurchaseTotal(prefix) {
	var total = 0.0;
	total += getVal("#id_service_tax");
	total += getVal("#id_education_cess");
	total += getVal("#id_higher_secondary");
	total += getVal("#id_tds");
	total = total - getVal("#id_discount");
	total += getVal("#id_round_off");

	$("#id_total").val(total.toFixed(2));
    };

    function reverse_calculate() {

    }

    function caluculate_total() {
    }
</script>

<div id="purchasers-popup">
<form id = "id_purchaser_form" name = "purchase_form"  method="post">{% csrf_token %}
  <div style="float:left;width:60%;%">
  <table>
    {{ form.as_table }}
  </table>
  </div>
  <div style="float:left;width:40%;">
    <h2> Passenger Information </h2>
    <div id="paxinfo_{{id}}"></div>
    <script>
      $(function() {
	$.ajax({
	    url: "/purchaseSaleInfo/{{id}}",
	    context: document.body,
	    cache: false,
	    success: function(data){
		$.each(data, function(k, v) {
		    $("#paxinfo_{{id}}").append("&nbsp;<hr />");
		    $.each(v, function(k, v) {
			$("#paxinfo_{{id}}").append("<li>"+k+" : "+v+"</li>");
		    });
		});
	    },
	    error: function(){
		alert('failure');
	    }
	});
    });
    </script>
  </div>
</form>
</div>

templates/themetours/update_services.html
<div id="services-popup">
<form id = "id_service_form" name="service_form"  method="post">{% csrf_token %}
{{ form.as_p }}
</form>
</div>